<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\UserController' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/ControllerTrait.php';
include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
include_once $this->targetDirs[3].'/src/Controller/UserController.php';
include_once $this->targetDirs[3].'/src/Service/UserService.php';
include_once $this->targetDirs[3].'/src/Repository/UserRepositoryInterface.php';
include_once $this->targetDirs[3].'/src/Repository/UserRepository.php';
include_once $this->targetDirs[3].'/src/Service/JwtAuth.php';
include_once $this->targetDirs[3].'/src/Service/Helpers.php';

$a = ($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php'));
$b = new \App\Service\JwtAuth($a);

$this->services['App\\Controller\\UserController'] = $instance = new \App\Controller\UserController(new \App\Service\UserService(new \App\Repository\UserRepository($a), $b, new \App\Service\Helpers($b)));

$instance->setContainer((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
    'http_kernel' => ['services', 'http_kernel', 'getHttpKernelService', false],
    'parameter_bag' => ['privates', 'parameter_bag', 'getParameterBagService', false],
    'request_stack' => ['services', 'request_stack', 'getRequestStackService', false],
    'router' => ['services', 'router', 'getRouterService', false],
    'session' => ['services', 'session', 'getSessionService.php', true],
], [
    'doctrine' => '?',
    'http_kernel' => '?',
    'parameter_bag' => '?',
    'request_stack' => '?',
    'router' => '?',
    'session' => '?',
]))->withContext('App\\Controller\\UserController', $this));

return $instance;
