<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBchXPUu\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBchXPUu/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerBchXPUu.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerBchXPUu\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerBchXPUu\srcApp_KernelProdContainer([
    'container.build_hash' => 'BchXPUu',
    'container.build_id' => '12a4b447',
    'container.build_time' => 1626093837,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBchXPUu');
