<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'user_create' => [[], ['_controller' => 'App\\Controller\\UserController::createAction'], [], [['text', '/user/create']], [], []],
    'user_login' => [[], ['_controller' => 'App\\Controller\\UserController::loginAction'], [], [['text', '/user/login']], [], []],
    'user_get_user' => [[], ['_controller' => 'App\\Controller\\UserController::getAction'], [], [['text', '/user/get']], [], []],
    'user_get_all' => [[], ['_controller' => 'App\\Controller\\UserController::getAllAction'], [], [['text', '/user/get-all']], [], []],
    'user_delete' => [[], ['_controller' => 'App\\Controller\\UserController::deleteAction'], [], [['text', '/user/delete']], [], []],
];
