<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPe85OHl\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPe85OHl/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPe85OHl.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPe85OHl\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPe85OHl\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Pe85OHl',
    'container.build_id' => '72acd987',
    'container.build_time' => 1626126364,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPe85OHl');
