<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_twig_error_test' => [['code', '_format'], ['_controller' => 'twig.controller.preview_error::previewErrorPageAction', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'list_invoices' => [[], ['_controller' => 'App\\Controller\\InvoiceController::listAction'], [], [['text', '/invoice/list']], [], []],
    'sum_of_invoices' => [['locationId'], ['_controller' => 'App\\Controller\\InvoiceController::sumAction'], [], [['variable', '/', '[^/]++', 'locationId', true], ['text', '/invoice/sum']], [], []],
];
